#!/bin/bash

#give permission to run this script
## chmod u+x slam_bash

#full path to the directory containing the .pcap files
path="/home/tiago/Desktop/vo/"

tempo=5
mkdir -p $path'pcd_temp'

cd $path
npcaps=$(ls -1 *.pcap 2>/dev/null | wc -l)
espera=$((npcaps*(tempo+1)))

#open roscore outside!
timeout $espera xterm -e "source ~/catkin_ws/devel/setup.bash && roscore" &

timer=$espera

#loop over the *.pcap files in the input directory 
for file in  $path*.pcap
do

	timer=$((timer-tempo))
	echo "processing: "$file" , timer: "$timer
	sleep $tempo

	#save .pcd files for all pcap frames 
	timeout $tempo xterm -e "cd "$path"pcd_temp && source ~/catkin_ws/devel/setup.bash && rosrun pcl_ros pointcloud_to_pcd input:=/velodyne_points" &

	#process the .pcap file
	timeout $tempo xterm -e 'source ~/catkin_ws/devel/setup.bash && sleep 1 && roslaunch velodyne_pointcloud VLP16_points.launch pcap:="'$file'" read_once:="true" max_range:="100" min_range:="2"' &

	#convert all pcd frames to a single .laz file
	sleep $tempo && xterm -e 'cd '$path' && ./pcd2laz -f pcd_temp -o '"${file%.pcap}.laz"' && cd pcd_temp && rm *.pcd'

done
